# Generated by Django 5.1.2 on 2026-09-24 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostel', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='students.student'),
        ),
        migrations.AddField(
            model_name='room',
            name='occupants',
            field=models.ManyToManyField(blank=True, related_name='hostel_rooms', to='students.student'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='hostel.room'),
        ),
    ]
