# Generated by Django 5.1.2 on 2026-09-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Fest', 'Fest'), ('Workshop', 'Workshop'), ('Sports', 'Sports'), ('Seminar', 'Seminar'), ('Other', 'Other')], default='Other', max_length=20)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
